<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AtelierResleriana.Compression\AtelierResleriana.Compression.csproj" />
    <ProjectReference Include="..\AtelierResleriana.Encryption\AtelierResleriana.Encryption.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AtelierResleriana.MessagePack">
      <HintPath>..\Assemblies\AtelierResleriana.MessagePack.dll</HintPath>
    </Reference>
    <Reference Include="AtelierResleriana.MessagePack.Annotations">
      <HintPath>..\Assemblies\AtelierResleriana.MessagePack.Annotations.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
