<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Uncompressed.tpk" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Uncompressed.tpk" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Generated\ClassIds.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ClassIds.tt</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Universal.Common" Version="8.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AtelierResleriana.Compression\AtelierResleriana.Compression.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Generated\ClassIds.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>ClassIds.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Generated\ClassIds.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ClassIds.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
